"""Benseditor -- a GameMaker-style 2D game engine for Python.

Object scripts normally only need::

    from benseditor import GameObject, keyboard_check, instance_create

Every public function is re-exported here.
"""

from __future__ import annotations

from .api import (
    angle_difference,
    approach,
    choose,
    clamp,
    collision_point,
    draw_circle,
    draw_get_color,
    draw_line,
    draw_rectangle,
    draw_set_alpha,
    draw_set_color,
    draw_sprite,
    draw_sprite_ext,
    draw_text,
    game_end,
    instance_create,
    instance_destroy,
    instance_exists,
    instance_find,
    instance_furthest,
    instance_list,
    instance_nearest,
    instance_number,
    irandom,
    irandom_range,
    keyboard_check,
    keyboard_check_pressed,
    keyboard_check_released,
    lengthdir_x,
    lengthdir_y,
    lerp,
    mouse_check_button,
    mouse_check_button_pressed,
    mouse_check_button_released,
    mouse_wheel,
    mouse_x,
    mouse_y,
    point_direction,
    point_distance,
    random_range,
    room_current,
    room_goto,
    room_height,
    room_restart,
    room_speed,
    room_width,
    shuffled,
    sign,
    string_height,
    string_width,
    view_get,
    view_set,
    wrap,
)
from .colors import (
    c_black,
    c_blue,
    c_gray,
    c_green,
    c_grey,
    c_orange,
    c_purple,
    c_red,
    c_white,
    c_yellow,
)
from .gameobject import GameObject

__version__ = "0.1.0"

__all__ = [
    "GameObject",
    "__version__",
    # instances
    "instance_create",
    "instance_destroy",
    "instance_exists",
    "instance_find",
    "instance_furthest",
    "instance_list",
    "instance_nearest",
    "instance_number",
    "collision_point",
    # rooms
    "room_current",
    "room_goto",
    "room_height",
    "room_restart",
    "room_speed",
    "room_width",
    "game_end",
    "view_get",
    "view_set",
    # input
    "keyboard_check",
    "keyboard_check_pressed",
    "keyboard_check_released",
    "mouse_check_button",
    "mouse_check_button_pressed",
    "mouse_check_button_released",
    "mouse_wheel",
    "mouse_x",
    "mouse_y",
    # drawing
    "draw_circle",
    "draw_get_color",
    "draw_line",
    "draw_rectangle",
    "draw_set_alpha",
    "draw_set_color",
    "draw_sprite",
    "draw_sprite_ext",
    "draw_text",
    "string_height",
    "string_width",
    # maths
    "angle_difference",
    "approach",
    "choose",
    "clamp",
    "irandom",
    "irandom_range",
    "lengthdir_x",
    "lengthdir_y",
    "lerp",
    "point_direction",
    "point_distance",
    "random_range",
    "shuffled",
    "sign",
    "wrap",
    # colours
    "c_black",
    "c_blue",
    "c_gray",
    "c_green",
    "c_grey",
    "c_orange",
    "c_purple",
    "c_red",
    "c_white",
    "c_yellow",
]
