/**
 * Writes `docs/` from `src/ui/docsData.ts`.
 *
 * The manual has one source. The editor's Docs tab renders that source
 * directly; these markdown files are generated from it so the offline copy can
 * never say something different.
 *
 *   node tools/build-docs.mjs           write the files
 *   node tools/build-docs.mjs --check   fail if they are out of date
 */
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'vite';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'docs');
const check = process.argv.includes('--check');

/** Load the TypeScript source module without a build step. */
async function loadDocs() {
  const server = await createServer({
    root,
    configFile: false,
    logLevel: 'error',
    server: { middlewareMode: true, hmr: false },
    // The manual imports nothing; skipping the dependency scan keeps this
    // quiet and quick.
    optimizeDeps: { noDiscovery: true, include: [] },
  });
  try {
    return await server.ssrLoadModule('/src/ui/docsData.ts');
  } finally {
    await server.close();
  }
}

const slug = (text) =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const fence = (code, lang = 'lua') => '```' + lang + '\n' + code.replace(/\t/g, '  ') + '\n```';

/**
 * The markdown carries both languages side by side: the Luau sample, then
 * the Python one under it; the Luau sentence, then a "Python:" paragraph
 * where the wording differs. Nothing is emitted for a missing twin, since the
 * Luau text then applies to both.
 */
const fences = (luau, python) => [fence(luau), python ? fence(python, 'python') : null];
const pythonNote = (text) => (text ? `Python: ${text}` : null);
const list = (items) => items.map((item) => `- ${item}`).join('\n');

function renderBlock(block) {
  const out = [];
  if (block.heading) out.push(`### ${block.heading}`);
  if (block.text) out.push(block.text, pythonNote(block.pythonText));
  if (block.list) out.push(list(block.list));
  if (block.pythonList) out.push('Python:', list(block.pythonList));
  if (block.table) {
    const { head, rows } = block.table;
    out.push(
      [
        `| ${head.join(' | ')} |`,
        `| ${head.map(() => '---').join(' | ')} |`,
        ...rows.map((row) => `| ${row.join(' | ')} |`),
      ].join('\n'),
    );
  }
  if (block.code) out.push(...fences(block.code, block.pythonCode));
  return out.filter(Boolean).join('\n\n');
}

function renderEntry(entry) {
  const title = entry.signature ? `${entry.name}${entry.signature}` : entry.name;
  const returns = entry.returns ? ` → ${entry.returns}` : '';

  const out = [`#### \`${title}\`${returns}`];
  // A method is called on an instance, and the receiver differs per language.
  if (entry.origin === 'method') {
    const luau = methodReceiver('luau') + title;
    const python = methodReceiver('python') + title;
    out.push(`\`${luau}\` in Luau, \`${python}\` in Python.`);
  }
  out.push(entry.summary);
  if (entry.detail) out.push(entry.detail, pythonNote(entry.pythonDetail));
  if (entry.example) out.push(...fences(entry.example, entry.pythonExample));
  return out.filter(Boolean).join('\n\n');
}

function renderSection(section) {
  const out = [`## ${section.title}`, `*${section.blurb}*`];
  if (section.pythonBlurb) out.push(`*Python: ${section.pythonBlurb}*`);
  for (const block of section.blocks ?? []) out.push(renderBlock(block));
  for (const entry of section.entries ?? []) out.push(renderEntry(entry));
  return out.join('\n\n');
}

const GENERATED = '<!-- Generated by tools/build-docs.mjs from src/ui/docsData.ts. Do not edit. -->';

function renderChapter(chapter, previous, next) {
  const parts = [
    GENERATED,
    `# ${chapter.title}`,
    chapter.sections.map((section) => `- [${section.title}](#${slug(section.title)})`).join('\n'),
    ...chapter.sections.map(renderSection),
  ];

  const links = [
    previous ? `← [${previous.title}](${slug(previous.title)}.md)` : null,
    '[Contents](README.md)',
    next ? `[${next.title}](${slug(next.title)}.md) →` : null,
  ].filter(Boolean);
  parts.push('---', links.join(' · '));

  return parts.join('\n\n') + '\n';
}

function renderIndex(chapters, entryCount) {
  const lines = [
    GENERATED,
    '# Benseditor manual',
    'A 2D game engine with GameMaker’s shape, scripted in Luau or Python, running entirely ' +
      'in the browser. This is the same text the editor shows under **Docs** — press F1 in ' +
      `the app to search all ${entryCount} documented names. Samples are given in both ` +
      'languages; see *Python mode* for the mapping between them.',
  ];

  for (const chapter of chapters) {
    lines.push(`## [${chapter.title}](${slug(chapter.title)}.md)`);
    lines.push(
      chapter.sections
        .map((section) => `- [${section.title}](${slug(chapter.title)}.md#${slug(section.title)}) — ${section.blurb}`)
        .join('\n'),
    );
  }

  lines.push('---', 'Generated from `src/ui/docsData.ts` by `npm run build:docs`.');
  return lines.join('\n\n') + '\n';
}

const { DOCS, ALL_ENTRIES, methodReceiver } = await loadDocs();

const files = new Map();
files.set('README.md', renderIndex(DOCS, ALL_ENTRIES.length));
DOCS.forEach((chapter, index) => {
  files.set(`${slug(chapter.title)}.md`, renderChapter(chapter, DOCS[index - 1], DOCS[index + 1]));
});

if (check) {
  const stale = [];
  for (const [name, contents] of files) {
    let current = null;
    try {
      current = await readFile(join(outDir, name), 'utf8');
    } catch {
      // Missing counts as stale.
    }
    if (current !== contents) stale.push(name);
  }

  const existing = await readdir(outDir).catch(() => []);
  for (const name of existing) {
    if (name.endsWith('.md') && !files.has(name)) stale.push(`${name} (orphaned)`);
  }

  if (stale.length) {
    console.error(`docs/ is out of date: ${stale.join(', ')}\nRun \`npm run build:docs\`.`);
    process.exit(1);
  }
  console.log(`docs/ is up to date (${files.size} files).`);
  process.exit(0);
}

// Rebuilt wholesale, so a renamed chapter cannot leave a stale file behind.
await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });
for (const [name, contents] of files) {
  await writeFile(join(outDir, name), contents, 'utf8');
}

console.log(`wrote ${files.size} files to docs/ (${ALL_ENTRIES.length} documented names)`);
